name: Rust

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:

env:
  CARGO_TERM_COLOR: always

jobs:
  format:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@stable
        with:
          components: rustfmt
      - run: |
          cargo fmt --check

  # It is not possible to run all the tests in a single
  # `cargo test` invocation. Specifically, `--all-targets`
  # does not cover doc tests [1].
  #
  # [1]: https://github.com/rust-lang/cargo/issues/6669
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@stable
      - name: Environment
        run: |
          sudo apt-get install -y libpam0g-dev bubblewrap pamtester
          echo 0 | sudo tee /proc/sys/kernel/apparmor_restrict_unprivileged_userns
      - name: Run tests
        run: |
          # Run tests (debug)
          cargo test \
            --workspace \
            --all-features \
            --verbose \
            --all-targets

          # Run tests (release).
          cargo test \
            --workspace \
            --all-features \
            --verbose \
            --all-targets \
            --release
      - name: Run doc tests
        run: |
          # Run all doc tests (debug).
          cargo test \
            --workspace \
            --all-features \
            --verbose \
            --doc

          # Run all doc tests (release).
          cargo test \
            --workspace \
            --all-features \
            --verbose \
            --doc \
            --release

  miri:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@nightly
        with:
          components: miri
      - name: Run Miri
        run: |
          # Exclude integration tests that actually call into PAM.
          cargo miri test \
            --workspace \
            --all-features \
            --verbose \
            --lib

  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@stable
        with:
          components: clippy
      - name: Clippy
        run: |
          cargo clippy \
            --workspace \
            --all-features \
            --all-targets \
            -- \
            --deny clippy::all \
            --deny clippy::pedantic \
            --deny clippy::nursery \
            --deny clippy::cargo \
            --deny warnings

  documentation:
    runs-on: ubuntu-latest
    env:
      RUSTDOCFLAGS: "-D warnings"
    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@stable
      - name: Documentation
        run: |
          cargo doc \
            --workspace \
            --all-features \
            --no-deps

  readme:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@stable
      - name: Verify README is in sync with the template
        run: |
          cargo install cargo-readme --version 3.3.2 --locked
          diff README.md <(cargo readme --project-root pam --template ../README.tpl)
